config/routes.rb
Storkypics::Application.routes.draw do

  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  resources :children
  resources :sendees
  resources :orders
  resources :subscribers
  resources :payment_notifications

  root to: 'static_pages#home'
  match '/how_it_works',   to: 'static_pages#how_it_works'
  match '/privacy_policy',   to: 'static_pages#privacy_policy'
  match '/user_agreement',   to: 'static_pages#user_agreement'
  match '/contact',   to: 'static_pages#contact'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :address,
  	:city, :state, :zip_code, :country, :children_attributes, :sendees_attributes, :new_order_path
  # attr_accessible :title, :body
  attr_accessor :new_order_path

  has_many :children, dependent: :destroy
  has_many :sendees, dependent: :destroy
  has_many :orders, dependent: :destroy
  accepts_nested_attributes_for :children, :sendees, allow_destroy: true

  #scope :pictures, lambda { |user| joins(:order).joins(:order => :pictures).where("pictures.user_id = ?", user.id) }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  #validate  :zip_code_length
  validates :country, presence: true

  def zip_code_length
    if !self.zip_code.blank? && self.zip_code.length != 5
      self.errors[:zip_code] = "must be 5 digits"
    end
  end

  STATES = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 
  	'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 
  	'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 
  	'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 
  	'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 
  	'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < Devise::RegistrationsController
  
  def new
    @user = User.new
    @user.children.new
    @user.sendees.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome! You have signed up successfully."
      UserMailer.new_user_alert(@user).deliver
      UserMailer.new_user_welcome(@user).deliver
      redirect_to root_path
      begin
        gb = Gibbon.new(ENV['MC_API_KEY'])
        list_id = gb.lists({:list_name => "Users"})["data"].first["id"]
        gb.list_subscribe(:id => list_id, :email_address => @user.email, :merge_vars => {'fname' => @user.first_name, 'lname' => @user.last_name }, :double_optin => false)
      rescue Gibbon::MailChimpError => e
        return
      end
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
    if request.referer.include?("orders/new")
      @new_order_path = true
    else
      @new_order_path = false
    end
  end

  def update
    @user = current_user
    if @user.update_with_password(params[:user])
      flash[:success] = "You updated your account successfully."
      if params[:user][:new_order_path] == "true"
        redirect_to new_order_path
      else
        redirect_to root_path
      end
    else
      render 'edit'
    end  
  end

  def destroy
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!, only: [:show, :update]

  def show
  	@user = User.find(params[:id])
  end

  def update
  	@user = current_user
		if @user.update_attributes(params[:user])
			flash[:success] = "Update successful"
			redirect_to root_path
		else
			flash[:error] = "Update unsuccessful. Please make sure all fields are filled out correctly."
			redirect_to root_path
		end
  end
end

app/views/users/user_registrations/_little_one_fields.html.erb
<div class="span4">
	<div style="float:left;margin-bottom:15px;">
		<div style="float:left;">
			<div class="flabel">First Name</div>
			<%= f.text_field :first_name, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
		</div>
		<div style="float:left;">
			<div class="flabel">Last Name</div>
			<%= f.text_field :last_name, required: true, style: "width:120px;font-size:110%;" %>
		</div>
	</div>
</div>
<div class="span4">
	<div style="clear:both;">
		<div class="flabel">Birthday</div>
		<% if f.object.birthday? %>
			<%= f.date_select :birthday, {order: [:month, :day, :year], 
										  start_year: Time.now.year - 15, 
										  end_year: Time.now.year}, 
										  {style: "width:25%;"} %>
		<% else %>
			<%= f.date_select :birthday, {order: [:month, :day, :year],
										  start_year: Time.now.year - 15, 
										  end_year: Time.now.year, 
										  prompt: true}, 
										  {style: "width:25%;", 
										  required: true} %>
		<% end %>
	</div>
</div>

app/views/users/user_registrations/_sendee_fields.html.erb
<div>
	<span class="span4" style="margin-left:0;">
    <div style="float:left;margin-bottom:15px;">
			<div style="float:left;">
		    <div class="flabel">First Name</div>
		    <%= f.text_field :first_name, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
			</div>
			<div style="float:left;">
		    <div class="flabel">Last Name</div>
		    <%= f.text_field :last_name, required: true, style: "width:120px;font-size:110%;" %>
			</div>
			<div style="float:left;">
		    <div class="flabel">Relationship to Child</div>
		    <%= f.select :relationship, Sendee::RELATIONSHIPS, { include_blank: true, required: true }, style: "width:288px;" %>
			</div>
			<div style="float:left;">
				<div class="flabel">Address</div>
				<%= f.text_field :address, required: true, style: "font-size:110%;" %>
	    </div>
    </div>
	</span>
	<span class="span6">
		<div style="float:left;">
	    <div style="float:left;">
		    <div class="flabel">City</div>
		    <%= f.text_field :city, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
			</div>
			<div style="float:left;">
		    <div class="flabel">State/Province</div>
		    <%= f.text_field :state, style: "width:120px;font-size:110%;" %>
			</div>
			<div style="float:left;">
				<div class="flabel">Zip/Postal Code</div>
				<%= f.text_field :zip_code, required: true, style: "font-size:110%;margin-right:25px;" %>
	    </div>
	    <div style="float:left;">
				<div class="flabel">Country</div>
				<%= f.country_select :country, ["United States"], {}, {style: "width:285px;"} %>
	    </div>
    </div>
    <%= f.hidden_field :_destroy %>
		<%= link_to "Remove", '#', class: "remove_fields", 
			style: "position:relative;bottom:200px;left:325px;
							font-family: 'BebasRegular';
							letter-spacing: .05em;
							word-spacing: .2em;" %>
	</span>
</div>

app/views/users/user_registrations/_you_fields.html.erb
<div class="row">
  <div class="span4">
		<div style="float:left;margin-bottom:15px;">
			<div style="float:left;">
				<div class="flabel">First Name</div>
				<%= f.text_field :first_name, autofocus: true, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
			</div>
			<div style="float:left;">
				<div class="flabel">Last Name</div>
				<%= f.text_field :last_name, required: true, style: "width:120px;font-size:110%;" %>
			</div>
		</div>
		<div style="clear:both;">
			<div class="flabel">Email</div>
			<%= f.email_field :email, required: true, style: "font-size:110%;" %>
		</div>
		<div style="float:left;margin-bottom:15px;">
			<div style="float:left;">
				<div class="flabel">Password</div>
				<%= f.password_field :password, required: true, style: "font-size:110%;" %>
			</div>
			<div style="float:left;">
				<div class="flabel">Confirmation</div>
				<%= f.password_field :password_confirmation, required: true, style: "font-size:110%;" %>
			</div>
		</div>
	</div>
	<div class="span4">
		<div>
			<div class="flabel">Address</div>
			<%= f.text_field :address, required: true, style: "font-size:110%;" %>
		</div>
		<div style="float:left;margin-bottom:15px;">
			<div style="float:left;">
				<div class="flabel">City</div>
				<%= f.text_field :city, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
			</div>
			<div style="float:left;">
				<div class="flabel">State/Province</div>
				<%= f.text_field :state, style: "width:120px;" %>
			</div>
		</div>
		<div style="clear:both;">
			<div class="flabel">Zip/Postal Code</div>
			<%= f.text_field :zip_code, required: true, style: "font-size:110%;" %>
		</div>
		<div style="float:left;">
				<div class="flabel">Country</div>
				<%= f.country_select :country, ["United States"], {}, {style: "width:285px;"} %>
	    </div>
	</div>
</div>

app/views/users/user_registrations/edit.html.erb
<h2>Edit Account Info</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="row">
    <div class="span4">
      <div style="float:left;margin-bottom:15px;">
        <div style="float:left;">
          <div class="flabel">First Name</div>
          <%= f.text_field :first_name, :autofocus => true, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
        </div>
        <div style="float:left;">
          <div class="flabel">Last Name</div>
          <%= f.text_field :last_name, required: true, style: "width:120px;font-size:110%;" %>
        </div>
      </div>
      <div style="clear:both;">
        <div class="flabel">Email</div>
        <%= f.email_field :email, required: true, style: "font-size:110%;" %>
      </div>
      <div style="float:left;margin-bottom:15px;">
        <div style="float:left;">
          <div class="flabel">Password</div>
          <%= f.password_field :password, :autocomplete => "off", style: "width:120px;margin-right:17px;font-size:110%;" %>
        </div>
        <div style="float:left;">
          <div class="flabel">Confirmation</div>
          <%= f.password_field :password_confirmation, style: "width:120px;font-size:110%;" %>
        </div>
        <div style="float:left;">(leave blank if you don't want to change it)</div>
        <div style="float:left;">
          <div class="flabel">Current Password</div>
          <%= f.password_field :current_password, required: true %>
          <div style="float:left;">(we need your current password to confirm your changes)</div>
        </div>
      </div>
    </div>
    <div class="span4">
      <div>
        <div class="flabel">Address</div>
        <%= f.text_field :address, required: true, style: "font-size:110%;" %>
      </div>
      <div style="float:left;margin-bottom:15px;">
        <div style="float:left;">
          <div class="flabel">City</div>
          <%= f.text_field :city, required: true, style: "width:120px;margin-right:17px;font-size:110%;" %>
        </div>
        <div style="float:left;">
          <div class="flabel">State/Province</div>
          <%= f.text_field :state, style: "width:120px;font-size:110%;" %>
        </div>
      </div>
      <div style="clear:both;">
        <div class="flabel">Zip/Postal Code</div>
        <%= f.text_field :zip_code, required: true, style: "font-size:110%;" %>
      </div>
      <div style="float:left;margin-top:15px;">
        <div class="flabel">Country</div>
        <%= f.country_select :country, ["United States"], {}, {style: "width:285px;"} %>
      </div>
    </div>
  </div>

  <%= f.hidden_field :new_order_path, value: @new_order_path %>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div><%= f.submit "Update", class: "submit" %></div>
<% end %>

<br>
<div>
  Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %>.
</div>

<%= link_to "Back", :back %>

app/views/users/user_registrations/new.html.erb
<h1>Sign up</h1>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <h2>You</h2>
  <%= render 'you_fields', f: f %>

	<h2>Your Little One</h2>
	<div class="row">
    <%= f.fields_for :children do |builder| %>
      <%= render 'little_one_fields', f: builder %>
    <% end %>
  </div>

	<h2 style="margin-bottom:0px;">
    <a href="#" rel="tooltip" 
       title="At least one recipient is required"
       style="color:#f15e3e;">
       Your Distribution List</a>
  </h2>
  <%= f.fields_for :sendees do |builder| %>
    <%= render 'sendee_fields', f: builder %>
  <% end %>
  <span class="links"><%= link_to_add_fields "Add Another!", f, :sendees %></span>
  
	<div style="clear:both;"><%= f.submit "Sign up", class: "submit", style: "margin-top:25px;" %></div>
<% end %>

<div style="margin:20px 0 0 0"><%= render "devise/shared/links" %></div>