config/routes.rb
Storkypics::Application.routes.draw do

  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  resources :children
  resources :sendees
  resources :orders
  resources :subscribers
  resources :payment_notifications

  root to: 'static_pages#home'
  match '/how_it_works',   to: 'static_pages#how_it_works'
  match '/privacy_policy',   to: 'static_pages#privacy_policy'
  match '/user_agreement',   to: 'static_pages#user_agreement'
  match '/contact',   to: 'static_pages#contact'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :address,
  	:city, :state, :zip_code, :country, :children_attributes, :sendees_attributes, :new_order_path
  # attr_accessible :title, :body
  attr_accessor :new_order_path

  has_many :children, dependent: :destroy
  has_many :sendees, dependent: :destroy
  has_many :orders, dependent: :destroy
  accepts_nested_attributes_for :children, :sendees, allow_destroy: true

  #scope :pictures, lambda { |user| joins(:order).joins(:order => :pictures).where("pictures.user_id = ?", user.id) }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  #validate  :zip_code_length
  validates :country, presence: true

  def zip_code_length
    if !self.zip_code.blank? && self.zip_code.length != 5
      self.errors[:zip_code] = "must be 5 digits"
    end
  end

  STATES = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 
  	'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 
  	'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 
  	'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 
  	'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 
  	'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!, only: [:show, :update]

  def show
  	@user = User.find(params[:id])
  end

  def update
  	@user = current_user
		if @user.update_attributes(params[:user])
			flash[:success] = "Update successful"
			redirect_to root_path
		else
			flash[:error] = "Update unsuccessful. Please make sure all fields are filled out correctly."
			redirect_to root_path
		end
  end
end

app/views/users/_home.html.erb
<% if Picture.purchased_by_user(current_user).all != [] %>
<div id="myCarousel" class="carousel slide" style="margin-left:auto;margin-right:auto;width:500px;margin-top:50px;">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <% Picture.purchased_by_user(current_user)[1..-1].each_with_index do |picture, idx| %>
	    <li data-target="#myCarousel" data-slide-to="<%= idx + 1 %>"></li>
    <% end %>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
    	<%= image_tag(Picture.purchased_by_user(current_user).first.pic.url(:large)) %>
    	<div class="carousel-caption">
    		<h2>To Send More Pics Click <%= link_to "Here", new_order_path %>!</h2>
    	</div>
    </div>
    <% Picture.purchased_by_user(current_user)[1..-1].each do |picture| %>
	    <div class="item">
	    	<%= image_tag(picture.pic.url(:large)) if picture.pic_content_type %>
		    <div class="carousel-caption">
	    		<h2>To Send More Pics Click <%= link_to "Here", new_order_path %>!</h2>
	    	</div>
	    </div>
    <% end %>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<% else %>
<div class="center-pic">
	<%= link_to image_tag('mailbox.jpg', class: "product-pic"), new_order_path %>
	<span style="position:relative;right:17px;"><%= link_to "Click Here To", new_order_path, class: "send-pics-btn" %></span><br><br>
	<%= link_to "Send Pics", new_order_path, class: "send-pics-btn" %>
</div>
<% end %>

<% if current_user.orders.purchased.any? %>
	<br><br>
	<h2>Your Order History</h2>

	<table class="order-table">
    <tr>
    	<th>Date</th>
    	<th>Pics</th>
    	<th>Recipients</th>
    	<th>Price</th>
    	<th>View Pics</th>
    </tr>
    <% current_user.orders.purchased.each do |order| %>
    	<tr>
	    	<td><%= order.created_at.strftime("%B %d, %Y") %></td>
	    	<td><%= order.pictures.count %></td>
	    	<td><%= order.recipient_count %></td>
	    	<td><%= "$#{order.recipient_count*3}" %></td>
	    	<td><%= link_to image_tag("glyphicons_319_sort.png"), order_path(order), target: "_blank" %></td>
	    </tr>
    <% end %>
	</table>
<% end %>

<br><br>
<h2>Your little one</h2>
<p>
	<span style="font-weight:bold;"><%= "#{current_user.children.first.first_name} #{current_user.children.first.last_name}" %></span><br>
	<%= "Born #{current_user.children.first.birthday.strftime("%B %d, %Y")}" %>
</p>
<div style="margin-top:10px;" class="links">
	<%= link_to "Edit", edit_child_path(current_user.children.first) %>
</div>

<br><br>
<h2>Your Distribution List</h2>

<div style="margin:10px 0;" class="links">
<%= link_to "Add Recipient", new_sendee_path %>
</div>

<p>
	<span style="font-weight:bold;"><%= "#{current_user.first_name} #{current_user.last_name}" %></span><br>
	<%= current_user.address %><br>
	<%= "#{current_user.city}, #{current_user.state}, #{current_user.zip_code}" %><br>
	<%= current_user.country %>
</p>
<div style="margin-top:10px;" class="links">
	<%= link_to "Edit", edit_user_registration_path(current_user) %>
</div><br>

<% current_user.sendees.each do |sendee| %>
	<p>
		<span style="font-weight:bold;"><%= "#{sendee.first_name} #{sendee.last_name}" %></span><br>
		<%= sendee.address %><br>
		<%= "#{sendee.city}, #{sendee.state}, #{sendee.zip_code}" %><br>
		<%= sendee.country %>
	</p>
	<div style="margin-top:10px;" class="links">
		<%= link_to "Edit", edit_sendee_path(sendee) %> | 
		<%= link_to "Delete", sendee, method: :delete, confirm: "You sure?" %>
	</div><br>
<% end %>