config/routes.rb
Storkypics::Application.routes.draw do

  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  resources :children
  resources :sendees
  resources :orders
  resources :subscribers
  resources :payment_notifications

  root to: 'static_pages#home'
  match '/how_it_works',   to: 'static_pages#how_it_works'
  match '/privacy_policy',   to: 'static_pages#privacy_policy'
  match '/user_agreement',   to: 'static_pages#user_agreement'
  match '/contact',   to: 'static_pages#contact'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/views/layouts/_footer.html.erb
<footer>
	<div id="copyright">
		<p>copyright 2013 Storkypics</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
			<%= link_to image_tag("storkypics-logo-small.png"), root_path, id: "logo" %>
			<div class="nav-collapse">
				<ul class="nav pull-right">
					<% if user_signed_in? %>
		      	<ul class="nav nav-pills links" style="position:relative;top:7px;">
		          <li><a href="#"><%= current_user.email %></a></li>
		          <li class="dropdown" id="menu1">
				    		<a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">Account<b class="caret"></b></a>
				    		<ul class="dropdown-menu">
				    		<li><%= link_to "How it Works", how_it_works_path %></li>
				    		<li><%= link_to "Home", root_path %></li>
				    		<li><%= link_to "Contact", contact_path %></li>
				      		<li><%= link_to "Take Our Survey", "https://www.surveymonkey.com/s/DXF9Z8G", target: "_blank" %></li>
				      		<li><%= link_to "Account Info", edit_user_registration_path %></li>
				      		<li class="divider"></li>
				      		<li><%= link_to 'Sign Out', destroy_user_session_path, method: "delete" %></li>
				    		</ul>
				  		</li>
				  		<li><%= link_to "Send Pics", new_order_path %></li>
						</ul>
			    <% else %>
			    	<ul class="nav nav-pills links" style="position:relative;top:7px;">
				  		<li><%= link_to "Sign Up", new_user_registration_path %></li>
				  		<li><%= link_to 'Sign In', new_user_session_path %></li>
				  		<li><%= link_to "Home", root_path %></li>
				  		<li><%= link_to "Contact", contact_path %></li>
				  		<li><%= link_to "How it Works", how_it_works_path %></li>
						</ul>
			    <% end %>
		    </ul>
	    </div>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
	  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag "/favicon.ico" %>
	  <%= render 'layouts/shim' %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= analytics_init if Rails.env.production? %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<div style="margin-left:auto;margin-right:auto;width:85%;">
				<% flash.each do |key, value| %>
					<div class="alert alert-#{key}">
						<a class="close" data-dismiss="alert">x</a>
						<%= content_tag(:div, value) %>
					</div>
				<% end %>
				
				<%= yield %>

				<%= render 'layouts/footer' %>
				<%= debug(params) if Rails.env.development? %>
			</div>
		</div>
	</body>
</html>